parserOptions: 
  ecmaVersion: 2017
  sourceType: module
env: 
  node: true
  es6: true
extends: eslint:recommended
rules: 
  no-console: off
  no-mixed-spaces-and-tabs: warn
  no-unused-vars: ["warn", { "vars": "local"}]
  class-methods-use-this: warn
  no-confusing-arrow: warn
  curly: ["error", "multi-line"]
  no-eval: error
  no-implied-eval: error
  no-trailing-spaces: warn
  no-lonely-if: warn
  no-useless-rename: warn
  arrow-body-style: ["error", "as-needed"]
  no-useless-concat: warn
  no-useless-return: warn
  no-multi-spaces: warn
  indent: ["warn", 2]
  no-tabs: warn
  func-call-spacing: ["warn", "never"]
  comma-spacing: ["warn", { "before": false, "after": true }]
  space-in-parens: ["error", "never"]
  space-infix-ops: warn